name: dbt_attio
version: "0.1.0"
config-version: 2

require-dbt-version: ">=1.3.0,<2.0.0"

profile: dbt_attio

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_attio:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
